"""
agents/minimax_media_agent/voices.py — MiniMax system-voice registry.

The LLM never sees this table in the system prompt (would bloat context).
Instead it is surfaced on demand through the ``list_system_voices`` tool,
optionally filtered by language substring.

Keep this list up to date with the MiniMax System Voice ID docs.  For
voices newly published by MiniMax, the Get Voice API can be polled at
runtime — extending that path is left for a future tool.
"""

from __future__ import annotations

from typing import Optional

# (language, voice_id, display_name)
SYSTEM_VOICES: tuple[tuple[str, str, str], ...] = (
    # English
    ("English", "English_expressive_narrator", "Expressive Narrator"),
    ("English", "English_radiant_girl", "Radiant Girl"),
    ("English", "English_magnetic_voiced_man", "Magnetic-voiced Male"),
    ("English", "English_compelling_lady1", "Compelling Lady"),
    ("English", "English_Aussie_Bloke", "Aussie Bloke"),
    ("English", "English_captivating_female1", "Captivating Female"),
    ("English", "English_Upbeat_Woman", "Upbeat Woman"),
    ("English", "English_Trustworth_Man", "Trustworthy Man"),
    ("English", "English_CalmWoman", "Calm Woman"),
    ("English", "English_UpsetGirl", "Upset Girl"),
    ("English", "English_Gentle-voiced_man", "Gentle-voiced Man"),
    ("English", "English_Whispering_girl", "Whispering girl"),
    ("English", "English_Diligent_Man", "Diligent Man"),
    ("English", "English_Graceful_Lady", "Graceful Lady"),
    ("English", "English_ReservedYoungMan", "Reserved Young Man"),
    ("English", "English_PlayfulGirl", "Playful Girl"),
    ("English", "English_ManWithDeepVoice", "Man With Deep Voice"),
    ("English", "English_MaturePartner", "Mature Partner"),
    ("English", "English_FriendlyPerson", "Friendly Guy"),
    ("English", "English_MatureBoss", "Bossy Lady"),
    ("English", "English_Debator", "Male Debater"),
    ("English", "English_LovelyGirl", "Lovely Girl"),
    ("English", "English_Steadymentor", "Reliable Man"),
    ("English", "English_Deep-VoicedGentleman", "Deep-voiced Gentleman"),
    ("English", "English_Wiselady", "Wise Lady"),
    ("English", "English_CaptivatingStoryteller", "Captivating Storyteller"),
    ("English", "English_DecentYoungMan", "Decent Young Man"),
    ("English", "English_SentimentalLady", "Sentimental Lady"),
    ("English", "English_ImposingManner", "Imposing Queen"),
    ("English", "English_SadTeen", "Teen Boy"),
    ("English", "English_PassionateWarrior", "Passionate Warrior"),
    ("English", "English_WiseScholar", "Wise Scholar"),
    ("English", "English_Soft-spokenGirl", "Soft-Spoken Girl"),
    ("English", "English_SereneWoman", "Serene Woman"),
    ("English", "English_ConfidentWoman", "Confident Woman"),
    ("English", "English_PatientMan", "Patient Man"),
    ("English", "English_Comedian", "Comedian"),
    ("English", "English_BossyLeader", "Bossy Leader"),
    ("English", "English_Strong-WilledBoy", "Strong-Willed Boy"),
    ("English", "English_StressedLady", "Stressed Lady"),
    ("English", "English_AssertiveQueen", "Assertive Queen"),
    ("English", "English_AnimeCharacter", "Female Narrator"),
    ("English", "English_Jovialman", "Jovial Man"),
    ("English", "English_WhimsicalGirl", "Whimsical Girl"),
    ("English", "English_Kind-heartedGirl", "Kind-Hearted Girl"),
    # Chinese (Mandarin)
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Reliable_Executive", "Reliable Executive"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_News_Anchor", "News Anchor"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Unrestrained_Young_Man", "Unrestrained Young Man"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Mature_Woman", "Mature Woman"),
    ("Chinese (Mandarin)", "Arrogant_Miss", "Arrogant Miss"),
    ("Chinese (Mandarin)", "Robot_Armor", "Robot Armor"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Kind-hearted_Antie", "Kind-hearted Antie"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_HK_Flight_Attendant", "HK Flight Attendant"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Humorous_Elder", "Humorous Elder"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Gentleman", "Gentleman"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Warm_Bestie", "Warm Bestie"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Stubborn_Friend", "Stubborn Friend"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Sweet_Lady", "Sweet Lady"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Southern_Young_Man", "Southern Young Man"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Wise_Women", "Wise Women"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Gentle_Youth", "Gentle Youth"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Warm_Girl", "Warm Girl"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Male_Announcer", "Male Announcer"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Kind-hearted_Elder", "Kind-hearted Elder"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Cute_Spirit", "Cute Spirit"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Radio_Host", "Radio Host"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Lyrical_Voice", "Lyrical Voice"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Straightforward_Boy", "Straightforward Boy"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Sincere_Adult", "Sincere Adult"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Gentle_Senior", "Gentle Senior"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Crisp_Girl", "Crisp Girl"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Pure-hearted_Boy", "Pure-hearted Boy"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Soft_Girl", "Soft Girl"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_IntellectualGirl", "Intellectual Girl"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Warm_HeartedGirl", "Warm-hearted Girl"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Laid_BackGirl", "Laid-back Girl"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_ExplorativeGirl", "Explorative Girl"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_Warm-HeartedAunt", "Warm-hearted Aunt"),
    ("Chinese (Mandarin)", "Chinese (Mandarin)_BashfulGirl", "Bashful Girl"),
    # Japanese
    ("Japanese", "Japanese_IntellectualSenior", "Intellectual Senior"),
    ("Japanese", "Japanese_DecisivePrincess", "Decisive Princess"),
    ("Japanese", "Japanese_LoyalKnight", "Loyal Knight"),
    ("Japanese", "Japanese_DominantMan", "Dominant Man"),
    ("Japanese", "Japanese_SeriousCommander", "Serious Commander"),
    ("Japanese", "Japanese_ColdQueen", "Cold Queen"),
    ("Japanese", "Japanese_DependableWoman", "Dependable Woman"),
    ("Japanese", "Japanese_GentleButler", "Gentle Butler"),
    ("Japanese", "Japanese_KindLady", "Kind Lady"),
    ("Japanese", "Japanese_CalmLady", "Calm Lady"),
    ("Japanese", "Japanese_OptimisticYouth", "Optimistic Youth"),
    ("Japanese", "Japanese_GenerousIzakayaOwner", "Generous Izakaya Owner"),
    ("Japanese", "Japanese_SportyStudent", "Sporty Student"),
    ("Japanese", "Japanese_InnocentBoy", "Innocent Boy"),
    ("Japanese", "Japanese_GracefulMaiden", "Graceful Maiden"),
    # Cantonese
    ("Cantonese", "Cantonese_ProfessionalHost (F)", "Professional Female Host"),
    ("Cantonese", "Cantonese_GentleLady", "Gentle Lady"),
    ("Cantonese", "Cantonese_ProfessionalHost (M)", "Professional Male Host"),
    ("Cantonese", "Cantonese_PlayfulMan", "Playful Man"),
    ("Cantonese", "Cantonese_CuteGirl", "Cute Girl"),
    ("Cantonese", "Cantonese_KindWoman", "Kind Woman"),
    # Korean
    ("Korean", "Korean_AirheadedGirl", "Airheaded Girl"),
    ("Korean", "Korean_AthleticGirl", "Athletic Girl"),
    ("Korean", "Korean_AthleticStudent", "Athletic Student"),
    ("Korean", "Korean_BraveAdventurer", "Brave Adventurer"),
    ("Korean", "Korean_BraveFemaleWarrior", "Brave Female Warrior"),
    ("Korean", "Korean_BraveYouth", "Brave Youth"),
    ("Korean", "Korean_CalmGentleman", "Calm Gentleman"),
    ("Korean", "Korean_CalmLady", "Calm Lady"),
    ("Korean", "Korean_CaringWoman", "Caring Woman"),
    ("Korean", "Korean_CharmingElderSister", "Charming Elder Sister"),
    ("Korean", "Korean_CharmingSister", "Charming Sister"),
    ("Korean", "Korean_CheerfulBoyfriend", "Cheerful Boyfriend"),
    ("Korean", "Korean_CheerfulCoolJunior", "Cheerful Cool Junior"),
    ("Korean", "Korean_CheerfulLittleSister", "Cheerful Little Sister"),
    ("Korean", "Korean_ChildhoodFriendGirl", "Childhood Friend Girl"),
    ("Korean", "Korean_CockyGuy", "Cocky Guy"),
    ("Korean", "Korean_ColdGirl", "Cold Girl"),
    ("Korean", "Korean_ColdYoungMan", "Cold Young Man"),
    ("Korean", "Korean_ConfidentBoss", "Confident Boss"),
    ("Korean", "Korean_ConsiderateSenior", "Considerate Senior"),
    ("Korean", "Korean_DecisiveQueen", "Decisive Queen"),
    ("Korean", "Korean_DominantMan", "Dominant Man"),
    ("Korean", "Korean_ElegantPrincess", "Elegant Princess"),
    ("Korean", "Korean_EnchantingSister", "Enchanting Sister"),
    ("Korean", "Korean_EnthusiasticTeen", "Enthusiastic Teen"),
    ("Korean", "Korean_FriendlyBigSister", "Friendly Big Sister"),
    ("Korean", "Korean_GentleBoss", "Gentle Boss"),
    ("Korean", "Korean_GentleWoman", "Gentle Woman"),
    ("Korean", "Korean_HaughtyLady", "Haughty Lady"),
    ("Korean", "Korean_InnocentBoy", "Innocent Boy"),
    ("Korean", "Korean_IntellectualMan", "Intellectual Man"),
    ("Korean", "Korean_IntellectualSenior", "Intellectual Senior"),
    ("Korean", "Korean_LonelyWarrior", "Lonely Warrior"),
    ("Korean", "Korean_MatureLady", "Mature Lady"),
    ("Korean", "Korean_MysteriousGirl", "Mysterious Girl"),
    ("Korean", "Korean_OptimisticYouth", "Optimistic Youth"),
    ("Korean", "Korean_PlayboyCharmer", "Playboy Charmer"),
    ("Korean", "Korean_PossessiveMan", "Possessive Man"),
    ("Korean", "Korean_QuirkyGirl", "Quirky Girl"),
    ("Korean", "Korean_ReliableSister", "Reliable Sister"),
    ("Korean", "Korean_ReliableYouth", "Reliable Youth"),
    ("Korean", "Korean_SassyGirl", "Sassy Girl"),
    ("Korean", "Korean_ShyGirl", "Shy Girl"),
    ("Korean", "Korean_SoothingLady", "Soothing Lady"),
    ("Korean", "Korean_StrictBoss", "Strict Boss"),
    ("Korean", "Korean_SweetGirl", "Sweet Girl"),
    ("Korean", "Korean_ThoughtfulWoman", "Thoughtful Woman"),
    ("Korean", "Korean_WiseElf", "Wise Elf"),
    ("Korean", "Korean_WiseTeacher", "Wise Teacher"),
    # Spanish
    ("Spanish", "Spanish_SereneWoman", "Serene Woman"),
    ("Spanish", "Spanish_MaturePartner", "Mature Partner"),
    ("Spanish", "Spanish_CaptivatingStoryteller", "Captivating Storyteller"),
    ("Spanish", "Spanish_Narrator", "Narrator"),
    ("Spanish", "Spanish_WiseScholar", "Wise Scholar"),
    ("Spanish", "Spanish_Kind-heartedGirl", "Kind-hearted Girl"),
    ("Spanish", "Spanish_DeterminedManager", "Determined Manager"),
    ("Spanish", "Spanish_BossyLeader", "Bossy Leader"),
    ("Spanish", "Spanish_ReservedYoungMan", "Reserved Young Man"),
    ("Spanish", "Spanish_ConfidentWoman", "Confident Woman"),
    ("Spanish", "Spanish_ThoughtfulMan", "Thoughtful Man"),
    ("Spanish", "Spanish_Strong-WilledBoy", "Strong-willed Boy"),
    ("Spanish", "Spanish_SophisticatedLady", "Sophisticated Lady"),
    ("Spanish", "Spanish_RationalMan", "Rational Man"),
    ("Spanish", "Spanish_AnimeCharacter", "Anime Character"),
    ("Spanish", "Spanish_Deep-tonedMan", "Deep-toned Man"),
    ("Spanish", "Spanish_Fussyhostess", "Fussy hostess"),
    ("Spanish", "Spanish_SincereTeen", "Sincere Teen"),
    ("Spanish", "Spanish_FrankLady", "Frank Lady"),
    ("Spanish", "Spanish_Comedian", "Comedian"),
    ("Spanish", "Spanish_Debator", "Debator"),
    ("Spanish", "Spanish_ToughBoss", "Tough Boss"),
    ("Spanish", "Spanish_Wiselady", "Wise Lady"),
    ("Spanish", "Spanish_Steadymentor", "Steady Mentor"),
    ("Spanish", "Spanish_Jovialman", "Jovial Man"),
    ("Spanish", "Spanish_SantaClaus", "Santa Claus"),
    ("Spanish", "Spanish_Rudolph", "Rudolph"),
    ("Spanish", "Spanish_Intonategirl", "Intonate Girl"),
    ("Spanish", "Spanish_Arnold", "Arnold"),
    ("Spanish", "Spanish_Ghost", "Ghost"),
    ("Spanish", "Spanish_HumorousElder", "Humorous Elder"),
    ("Spanish", "Spanish_EnergeticBoy", "Energetic Boy"),
    ("Spanish", "Spanish_WhimsicalGirl", "Whimsical Girl"),
    ("Spanish", "Spanish_StrictBoss", "Strict Boss"),
    ("Spanish", "Spanish_ReliableMan", "Reliable Man"),
    ("Spanish", "Spanish_SereneElder", "Serene Elder"),
    ("Spanish", "Spanish_AngryMan", "Angry Man"),
    ("Spanish", "Spanish_AssertiveQueen", "Assertive Queen"),
    ("Spanish", "Spanish_CaringGirlfriend", "Caring Girlfriend"),
    ("Spanish", "Spanish_PowerfulSoldier", "Powerful Soldier"),
    ("Spanish", "Spanish_PassionateWarrior", "Passionate Warrior"),
    ("Spanish", "Spanish_ChattyGirl", "Chatty Girl"),
    ("Spanish", "Spanish_RomanticHusband", "Romantic Husband"),
    ("Spanish", "Spanish_CompellingGirl", "Compelling Girl"),
    ("Spanish", "Spanish_PowerfulVeteran", "Powerful Veteran"),
    ("Spanish", "Spanish_SensibleManager", "Sensible Manager"),
    ("Spanish", "Spanish_ThoughtfulLady", "Thoughtful Lady"),
    # Portuguese
    ("Portuguese", "Portuguese_SentimentalLady", "Sentimental Lady"),
    ("Portuguese", "Portuguese_BossyLeader", "Bossy Leader"),
    ("Portuguese", "Portuguese_Wiselady", "Wise lady"),
    ("Portuguese", "Portuguese_Strong-WilledBoy", "Strong-willed Boy"),
    ("Portuguese", "Portuguese_Deep-VoicedGentleman", "Deep-voiced Gentleman"),
    ("Portuguese", "Portuguese_UpsetGirl", "Upset Girl"),
    ("Portuguese", "Portuguese_PassionateWarrior", "Passionate Warrior"),
    ("Portuguese", "Portuguese_AnimeCharacter", "Anime Character"),
    ("Portuguese", "Portuguese_ConfidentWoman", "Confident Woman"),
    ("Portuguese", "Portuguese_AngryMan", "Angry Man"),
    ("Portuguese", "Portuguese_CaptivatingStoryteller", "Captivating Storyteller"),
    ("Portuguese", "Portuguese_Godfather", "Godfather"),
    ("Portuguese", "Portuguese_ReservedYoungMan", "Reserved Young Man"),
    ("Portuguese", "Portuguese_SmartYoungGirl", "Smart Young Girl"),
    ("Portuguese", "Portuguese_Kind-heartedGirl", "Kind-hearted Girl"),
    ("Portuguese", "Portuguese_Pompouslady", "Pompous lady"),
    ("Portuguese", "Portuguese_Grinch", "Grinch"),
    ("Portuguese", "Portuguese_Debator", "Debator"),
    ("Portuguese", "Portuguese_SweetGirl", "Sweet Girl"),
    ("Portuguese", "Portuguese_AttractiveGirl", "Attractive Girl"),
    ("Portuguese", "Portuguese_ThoughtfulMan", "Thoughtful Man"),
    ("Portuguese", "Portuguese_PlayfulGirl", "Playful Girl"),
    ("Portuguese", "Portuguese_GorgeousLady", "Gorgeous Lady"),
    ("Portuguese", "Portuguese_LovelyLady", "Lovely Lady"),
    ("Portuguese", "Portuguese_SereneWoman", "Serene Woman"),
    ("Portuguese", "Portuguese_SadTeen", "Sad Teen"),
    ("Portuguese", "Portuguese_MaturePartner", "Mature Partner"),
    ("Portuguese", "Portuguese_Comedian", "Comedian"),
    ("Portuguese", "Portuguese_NaughtySchoolgirl", "Naughty Schoolgirl"),
    ("Portuguese", "Portuguese_Narrator", "Narrator"),
    ("Portuguese", "Portuguese_ToughBoss", "Tough Boss"),
    ("Portuguese", "Portuguese_Fussyhostess", "Fussy hostess"),
    ("Portuguese", "Portuguese_Dramatist", "Dramatist"),
    ("Portuguese", "Portuguese_Steadymentor", "Steady Mentor"),
    ("Portuguese", "Portuguese_Jovialman", "Jovial Man"),
    ("Portuguese", "Portuguese_CharmingQueen", "Charming Queen"),
    ("Portuguese", "Portuguese_SantaClaus", "Santa Claus"),
    ("Portuguese", "Portuguese_Rudolph", "Rudolph"),
    ("Portuguese", "Portuguese_Arnold", "Arnold"),
    ("Portuguese", "Portuguese_CharmingSanta", "Charming Santa"),
    ("Portuguese", "Portuguese_CharmingLady", "Charming Lady"),
    ("Portuguese", "Portuguese_Ghost", "Ghost"),
    ("Portuguese", "Portuguese_HumorousElder", "Humorous Elder"),
    ("Portuguese", "Portuguese_CalmLeader", "Calm Leader"),
    ("Portuguese", "Portuguese_GentleTeacher", "Gentle Teacher"),
    ("Portuguese", "Portuguese_EnergeticBoy", "Energetic Boy"),
    ("Portuguese", "Portuguese_ReliableMan", "Reliable Man"),
    ("Portuguese", "Portuguese_SereneElder", "Serene Elder"),
    ("Portuguese", "Portuguese_GrimReaper", "Grim Reaper"),
    ("Portuguese", "Portuguese_AssertiveQueen", "Assertive Queen"),
    ("Portuguese", "Portuguese_WhimsicalGirl", "Whimsical Girl"),
    ("Portuguese", "Portuguese_StressedLady", "Stressed Lady"),
    ("Portuguese", "Portuguese_FriendlyNeighbor", "Friendly Neighbor"),
    ("Portuguese", "Portuguese_CaringGirlfriend", "Caring Girlfriend"),
    ("Portuguese", "Portuguese_PowerfulSoldier", "Powerful Soldier"),
    ("Portuguese", "Portuguese_FascinatingBoy", "Fascinating Boy"),
    ("Portuguese", "Portuguese_RomanticHusband", "Romantic Husband"),
    ("Portuguese", "Portuguese_StrictBoss", "Strict Boss"),
    ("Portuguese", "Portuguese_InspiringLady", "Inspiring Lady"),
    ("Portuguese", "Portuguese_PlayfulSpirit", "Playful Spirit"),
    ("Portuguese", "Portuguese_ElegantGirl", "Elegant Girl"),
    ("Portuguese", "Portuguese_CompellingGirl", "Compelling Girl"),
    ("Portuguese", "Portuguese_PowerfulVeteran", "Powerful Veteran"),
    ("Portuguese", "Portuguese_SensibleManager", "Sensible Manager"),
    ("Portuguese", "Portuguese_ThoughtfulLady", "Thoughtful Lady"),
    ("Portuguese", "Portuguese_TheatricalActor", "Theatrical Actor"),
    ("Portuguese", "Portuguese_FragileBoy", "Fragile Boy"),
    ("Portuguese", "Portuguese_ChattyGirl", "Chatty Girl"),
    ("Portuguese", "Portuguese_Conscientiousinstructor", "Conscientious Instructor"),
    ("Portuguese", "Portuguese_RationalMan", "Rational Man"),
    ("Portuguese", "Portuguese_WiseScholar", "Wise Scholar"),
    ("Portuguese", "Portuguese_FrankLady", "Frank Lady"),
    ("Portuguese", "Portuguese_DeterminedManager", "Determined Manager"),
    # French
    ("French", "French_Male_Speech_New", "Level-Headed Man"),
    ("French", "French_Female_News Anchor", "Patient Female Presenter"),
    ("French", "French_CasualMan", "Casual Man"),
    ("French", "French_MovieLeadFemale", "Movie Lead Female"),
    ("French", "French_FemaleAnchor", "Female Anchor"),
    ("French", "French_MaleNarrator", "Male Narrator"),
    # Indonesian
    ("Indonesian", "Indonesian_SweetGirl", "Sweet Girl"),
    ("Indonesian", "Indonesian_ReservedYoungMan", "Reserved Young Man"),
    ("Indonesian", "Indonesian_CharmingGirl", "Charming Girl"),
    ("Indonesian", "Indonesian_CalmWoman", "Calm Woman"),
    ("Indonesian", "Indonesian_ConfidentWoman", "Confident Woman"),
    ("Indonesian", "Indonesian_CaringMan", "Caring Man"),
    ("Indonesian", "Indonesian_BossyLeader", "Bossy Leader"),
    ("Indonesian", "Indonesian_DeterminedBoy", "Determined Boy"),
    ("Indonesian", "Indonesian_GentleGirl", "Gentle Girl"),
    # German
    ("German", "German_FriendlyMan", "Friendly Man"),
    ("German", "German_SweetLady", "Sweet Lady"),
    ("German", "German_PlayfulMan", "Playful Man"),
    # Russian
    ("Russian", "Russian_HandsomeChildhoodFriend", "Handsome Childhood Friend"),
    ("Russian", "Russian_BrightHeroine", "Bright Queen"),
    ("Russian", "Russian_AmbitiousWoman", "Ambitious Woman"),
    ("Russian", "Russian_ReliableMan", "Reliable Man"),
    ("Russian", "Russian_CrazyQueen", "Crazy Girl"),
    ("Russian", "Russian_PessimisticGirl", "Pessimistic Girl"),
    ("Russian", "Russian_AttractiveGuy", "Attractive Guy"),
    ("Russian", "Russian_Bad-temperedBoy", "Bad-tempered Boy"),
    # Italian
    ("Italian", "Italian_BraveHeroine", "Brave Heroine"),
    ("Italian", "Italian_Narrator", "Narrator"),
    ("Italian", "Italian_WanderingSorcerer", "Wandering Sorcerer"),
    ("Italian", "Italian_DiligentLeader", "Diligent Leader"),
    # Dutch
    ("Dutch", "Dutch_kindhearted_girl", "Kind-hearted girl"),
    ("Dutch", "Dutch_bossy_leader", "Bossy leader"),
    # Vietnamese
    ("Vietnamese", "Vietnamese_kindhearted_girl", "Kind-hearted girl"),
    # Arabic
    ("Arabic", "Arabic_CalmWoman", "Calm Woman"),
    ("Arabic", "Arabic_FriendlyGuy", "Friendly Guy"),
    # Turkish
    ("Turkish", "Turkish_CalmWoman", "Calm Woman"),
    ("Turkish", "Turkish_Trustworthyman", "Trustworthy man"),
    # Ukrainian
    ("Ukrainian", "Ukrainian_CalmWoman", "Calm Woman"),
    ("Ukrainian", "Ukrainian_WiseScholar", "Wise Scholar"),
    # Thai
    ("Thai", "Thai_male_1_sample8", "Serene Man"),
    ("Thai", "Thai_male_2_sample2", "Friendly Man"),
    ("Thai", "Thai_female_1_sample1", "Confident Woman"),
    ("Thai", "Thai_female_2_sample2", "Energetic Woman"),
    # Polish
    ("Polish", "Polish_male_1_sample4", "Male Narrator"),
    ("Polish", "Polish_male_2_sample3", "Male Anchor"),
    ("Polish", "Polish_female_1_sample1", "Calm Woman"),
    ("Polish", "Polish_female_2_sample3", "Casual Woman"),
    # Romanian
    ("Romanian", "Romanian_male_1_sample2", "Reliable Man"),
    ("Romanian", "Romanian_male_2_sample1", "Energetic Youth"),
    ("Romanian", "Romanian_female_1_sample4", "Optimistic Youth"),
    ("Romanian", "Romanian_female_2_sample1", "Gentle Woman"),
    # Greek
    ("Greek", "greek_male_1a_v1", "Thoughtful Mentor"),
    ("Greek", "Greek_female_1_sample1", "Gentle Lady"),
    ("Greek", "Greek_female_2_sample3", "Girl Next Door"),
    # Czech
    ("Czech", "czech_male_1_v1", "Assured Presenter"),
    ("Czech", "czech_female_5_v7", "Steadfast Narrator"),
    ("Czech", "czech_female_2_v2", "Elegant Lady"),
    # Finnish
    ("Finnish", "finnish_male_3_v1", "Upbeat Man"),
    ("Finnish", "finnish_male_1_v2", "Friendly Boy"),
    ("Finnish", "finnish_female_4_v1", "Assetive Woman"),
    # Hindi
    ("Hindi", "hindi_male_1_v2", "Trustworthy Advisor"),
    ("Hindi", "hindi_female_2_v1", "Tranquil Woman"),
    ("Hindi", "hindi_female_1_v2", "News Anchor"),
)


def format_voices(language: Optional[str] = None) -> str:
    """Return a Markdown-grouped voice list, optionally filtered by a
    language substring (case-insensitive).
    """
    needle = (language or "").strip().lower()
    hits: list[tuple[str, str, str]] = []
    for lang, vid, name in SYSTEM_VOICES:
        if not needle or needle in lang.lower():
            hits.append((lang, vid, name))
    if not hits:
        langs = sorted({lang for lang, _, _ in SYSTEM_VOICES})
        return (
            f"No voices found for '{language}'. Available languages: "
            + ", ".join(langs)
        )
    grouped: dict[str, list[tuple[str, str]]] = {}
    order: list[str] = []
    for lang, vid, name in hits:
        if lang not in grouped:
            grouped[lang] = []
            order.append(lang)
        grouped[lang].append((vid, name))
    lines: list[str] = []
    for lang in order:
        lines.append(f"## {lang}")
        for vid, name in grouped[lang]:
            lines.append(f"- `{vid}` — {name}")
        lines.append("")
    total = len(hits)
    header = (
        f"{total} system voice{'s' if total != 1 else ''} "
        + (f"matching '{language}':" if language else "available:")
    )
    return header + "\n\n" + "\n".join(lines).rstrip()
